# Generated by Django 4.0.7 on 2023-07-20 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_blog_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='blog_title',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='is_public',
        ),
    ]
