# Generated by Django 4.0.7 on 2023-07-20 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0003_remove_blog_blog_title_remove_blog_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='blog_title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
